---
# AWS 相關測試
# edit by sakana 2021/3/14
# 刪除 EC2 Key Pair
#
# 官方建議的方式
- hosts: localhost
  connection: local
  gather_facts: False
#

  vars_prompt:
#要求使用者輸入 access key id 與 secret access key
    - name: "aws_access_key_id"
      prompt: "Enter aws_access_key_id"
      private: no

    - name: "aws_secret_access_key"
      prompt: "Enter aws_secret_access_key"
      private: no

    - name: "aws_region"
      prompt: "請輸入 要執行的 AWS Region / Enter AWS Region: us-east-2 / ap-northeast-1"
      private: no
# us-east-2 爲 Ohio / ap-northeast-1 為 Tokyo
      default: us-east-2

#詢問 key name
    - name: "ec2_key_name"
      prompt: "請輸入要建立的 EC2 Key 名稱 / Enter ec2 key name: "
      private: no
      default: test-key-can-delete


  tasks:
    - name: Remove EC2 key pair
      ec2_key:
        aws_access_key: "{{ aws_access_key_id }}"
        aws_secret_key: "{{ aws_secret_access_key }}"
        name: "{{ ec2_key_name }}"
        region: "{{ aws_region }}"
        state: absent

