---
# AWS 相關測試
# edit by sakana 2021/3/14
# 建立 EC2 Key Pair
#
# 官方建議的方式
- hosts: localhost
  connection: local
  gather_facts: False
#

  vars_prompt:
#要求使用者輸入 access key id 與 secret access key
    - name: "aws_access_key_id"
      prompt: "請輸入要執行的 AWS Access Key ID / Enter aws_access_key_id"
      private: no

    - name: "aws_secret_access_key"
      prompt: "請輸入要執行的 AWS Secret Access Key / Enter aws_secret_access_key"
      private: no

    - name: "aws_region"
      prompt: "請輸入 要執行的 AWS Region / Enter AWS Region: us-east-2 / ap-northeast-1"
      private: no
# us-east-2 爲 Ohio / ap-northeast-1 為 Tokyo
      default: us-east-2

#詢問 key name
    - name: "ec2_key_name"
      prompt: "\n ==如果是在容器環境執行可以使用 docker cp 複製出來== \n 請輸入要建立的 EC2 Key 名稱, 建立完成會存放在家目錄 / Enter ec2 key name, it will save to home directory"
      private: no
      default: test-key-can-delete


  tasks:
    - name: Create EC2 key pair
      ec2_key:
        aws_access_key: "{{ aws_access_key_id }}"
        aws_secret_key: "{{ aws_secret_access_key }}"
        name: "{{ ec2_key_name }}"
        region: "{{ aws_region }}"
        state: present
#使用 register 之後來將 key 匯出  
      register: ec2_key_result

# 使用copy module 來將傳回的資訊複製成檔案, 並設定權限
    - name: Save private key
      copy:
        content: "{{ ec2_key_result.key.private_key }}"
        dest: "~/{{ec2_key_name}}.pem"
        mode: 0400

