---
# AWS 相關測試
# edit by sakana 2021/3/14
# 根據 Tag 啟動 EC2
#
# 官方建議的方式
- hosts: localhost
  connection: local
  gather_facts: False
#

  vars_prompt:
#要求使用者輸入 access key id 與 secret access key
    - name: "aws_access_key_id"
      prompt: "Enter aws_access_key_id"
      private: no

    - name: "aws_secret_access_key"
      prompt: "Enter aws_secret_access_key"
      private: no

    - name: "aws_region"
      prompt: "請輸入 要執行的 AWS Region / Enter AWS Region: us-east-2 / ap-northeast-1"
      private: no
# us-east-2 爲 Ohio / ap-northeast-1 為 Tokyo
      default: us-east-2

# 設定 Tag
    - name: "instance_tags_value"
      prompt: '"Enter the tag name and value. example: {"Env":"Lab"} or {"Env":"Lab","Name":"maxtest"}  "'
      private: no
      default: {"Env":"Lab","Name":"maxtest"}


  tasks:
    - name: Start EC2 by Tag
      ec2:
        aws_access_key: "{{ aws_access_key_id }}"
        aws_secret_key: "{{ aws_secret_access_key }}"
        region: "{{ aws_region }}"
        instance_tags: "{{ instance_tags_value }}"
        state: running

