#########################################################  
# 
# edit by sakana 2020/3/12
#
# 不放心的話, 可以用 ansible-playbook --check 來 Dry Run
#########################################################  

- name: Install openjdk
# use group, 所以記得去把要套用的主機加入 openjdk 群組內
  hosts: openjdk
#  sudo: True
  become: True

# 本來想要用單一套件名稱套用常用OS, 但是 openjdk 在不同 OS 名稱不一樣, 故放棄
#  vars_prompt:
#    - name: "openjdk_version"
#      prompt: "Enter openjdk package name, ex: java-1.8.0-openjdk"
#      private: no
#      default: java-1.8.0-openjdk


  tasks:
#-------------------------------------------------------  
#    - name: test setup moudule
#      setup: filter=ansible_distribution

#-------------------------------------------------------  
# openSUSE

    - name: Install openjdk with openSUSE Leap
      zypper: 
        name:
          - java-1_8_0-openjdk
      when: ansible_distribution == "openSUSE Leap"

# 舊的方式 with_item 已經被棄用
#    - name: Install docker with openSUSE Leap
#      zypper: name={{ item }}
#      with_items:
#        - docker
#        - curl
#      when: ansible_distribution == "openSUSE Leap"

#-------------------------------------------------------  
#  CentOS 

    - name: Install openjdk with CentOS
      yum:
        name:
          - java-1.8.0-openjdk 
      when: ansible_distribution == "CentOS"

#-------------------------------------------------------  
# Ubuntu

    - name: Install openjdk with Ubuntu
      apt: 
        name:
          - openjdk-8-jdk
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

#-------------------------------------------------------  



