---
# Azure VM 相關測試
# edit by sakan 2020/4/4
- name: use when conditionals and setup module
  hosts: localhost
  vars_prompt:
    - name: "vm_name"
      prompt: "Enter VM name your want to remove"
      private: no
      default: test01

    - name: "resource_group"
      prompt: "Enter resource group name"
      private: no
      default: sakanastudy

  tasks:
   - name: Remove Azure test VM
     azure_rm_virtualmachine:
       resource_group: "{{ resource_group }}"
       name: "{{ vm_name }}"
       state: absent
